<FirstScreen>:
    GridLayout:
        cols:1
        Image:
            id : img
            size_hint_y: 0.8
            padding : 10
        TextInput:
            id : user_query
            size_hint_y: 0.1
        Button:
            text:'Search image'
            size_hint_y: 0.1
            on_press : root.search_image()

<RootWidget>:
    FirstScreen:
        id : first_screen
        name : 'first_screen'